apiVersion: v1
kind: Service
metadata:
  name: nemotron-nim
  namespace: nim
spec:
  selector:
    app: nemotron-nim
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
